services:
  web:
    build: .
    environment:
      - NODE_ENV=production
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.personalsite.rule=${TRAEFIK_RULE:-Host(`${DOMAIN}`)}"
      - "traefik.http.routers.personalsite.entrypoints=web"
      - "traefik.http.routers.personalsite.service=personalsite"
      - "traefik.http.routers.personalsite-secure.rule=${TRAEFIK_RULE:-Host(`${DOMAIN}`)}"
      - "traefik.http.routers.personalsite-secure.entrypoints=websecure"
      - "traefik.http.routers.personalsite-secure.tls=true"
      - "traefik.http.routers.personalsite-secure.tls.certresolver=${TRAEFIK_CERTRESOLVER:-}"
      - "traefik.http.routers.personalsite-secure.tls.domains[0].main=${TRAEFIK_TLS_MAIN:-}"
      - "traefik.http.routers.personalsite-secure.tls.domains[0].sans=${TRAEFIK_TLS_SANS:-}"
      - "traefik.http.routers.personalsite-secure.service=personalsite"
      - "traefik.http.services.personalsite.loadbalancer.server.port=3000"

networks:
  web:
    external: true
